// const Carrier_DB = {heading:["Associate Consultant Audit","Associate Consultant Appsec","Associate Consultant Network Security","Anaylist","Senior Specialist"],pera:[
//     ["1. Experience conducting full PCIDSS v3.2.1 /v4,0 audits for banks, payment gateways.","2. Able to scope the requirements for PCIDSS. Well versed in PCIDSS Location mandatorily NCR region Has experience handling RBI audits PAPG, PSS,", "3.etc Good communication skills Able to multitask"],
//     ["1. To perform Web and Mobile Application and API Penetration testing","2. Client interaction","3. perform retest post confirmation on the fixes","4. Followup with the relevant stakeholders on the remediation of open vulnerabilities"],
//     ["1. To perform Vulnerability Assessment and Penetration Testing of Network and Infrastructure","2. Client interaction","3. perform rescan post confirmation on the fixes","4. Followup with the relevant stakeholders on the remediation of open vulnerabilities"],
//     ["1· VAPT of Network and Infrastructure","2.  Good understanding of Networking, Operating system, and security concepts","3. Good written and spoken communication skills","4. Ability to do report walkthrough with relevant stakeholders","5. Hands-on experience with Nessus, Qualysguard, nmap and Kali Linux tools"],
//     ["1. VAPT of Network and Infrastructure","2. Good understanding of Networking, Operating system, and security concepts","3. Good written and spoken communication skills","4. Ability to do report walkthrough with relevant stakeholders","5. Hands-on experience with Nessus, Qualysguard, nmap and Kali Linux tools"],

// ], year:["3 years to 5 years","3 years to 5 years","3 years to 5 years","1 years to 2 years","4 years to 5 years"], loc:["Calicut","Calicut","Calicut","Calicut","Bangalore"]}


const Carrier_DB = [
    {id:"0", heading:"Associate Consultant Audit",pera:["1. Experience conducting full PCIDSS v3.2.1 /v4,0 audits for banks, payment gateways.","2. Able to scope the requirements for PCIDSS. Well versed in PCIDSS Location mandatorily NCR region Has experience handling RBI audits PAPG, PSS,", "3.etc Good communication skills Able to multitask"],year:"3 years to 5 years",loc:"Calicut"},
    {id:"1", heading:"Associate Consultant Appsec",pera:["1. To perform Web and Mobile Application and API Penetration testing","2. Client interaction","3. perform retest post confirmation on the fixes","4. Followup with the relevant stakeholders on the remediation of open vulnerabilities"],year:"3 years to 5 years",loc:"Calicut"},
    {id:"2", heading:"Associate Consultant Network Security",pera:["1. To perform Vulnerability Assessment and Penetration Testing of Network and Infrastructure","2. Client interaction","3. perform rescan post confirmation on the fixes","4. Followup with the relevant stakeholders on the remediation of open vulnerabilities"],year:"3 years to 5 years",loc:"Calicut"},
    {id:"3", heading:"Anaylist",pera:["1· VAPT of Network and Infrastructure","2.  Good understanding of Networking, Operating system, and security concepts","3. Good written and spoken communication skills","4. Ability to do report walkthrough with relevant stakeholders","5. Hands-on experience with Nessus, Qualysguard, nmap and Kali Linux tools"],year:"1 years to 2 years",loc:"Calicut"},
    {id:"4", heading:"Senior Specialist",pera:    ["1. VAPT of Network and Infrastructure","2. Good understanding of Networking, Operating system, and security concepts","3. Good written and spoken communication skills","4. Ability to do report walkthrough with relevant stakeholders","5. Hands-on experience with Nessus, Qualysguard, nmap and Kali Linux tools"],year:"3 years to 5 years",loc:"Bangalore"}
]

export default Carrier_DB;